version: '3'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: migueabellan.github.io
    command: jekyll serve --safe --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
